# Generated by Django 3.2.11 on 2023-05-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_thread_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
