# Generated by Django 4.2 on 2023-04-16 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="contents",
            new_name="content",
        ),
    ]
