# Generated by Django 4.2 on 2023-04-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_contents_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="item_images"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
