# Generated by Django 4.2 on 2023-04-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_post_price_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=90),
        ),
    ]
